### ISSUE TITLE
ir.ilmili.telegraph找不到软件设置入口 版本 T8.7.4 - P10.0.1

### ISSUE THREAD

**Issue by xushet** [cinit/TMoe#35]
设置界面如图
![Screenshot_20220702-211712_Shady启动器.png](https://user-images.githubusercontent.com/34502902/177002477-08451a61-bb4f-4fb7-bde5-7699f20951ab.png)

lsposed作用域![Screenshot_20220702-212858_Shady启动器.png](https://user-images.githubusercontent.com/34502902/177003022-10707748-c0ca-4382-b99b-2516a18a0656.png)

官方版能正常显示
![Screenshot_20220702-213017_Shady启动器.png](https://user-images.githubusercontent.com/34502902/177003030-6c17a4ba-a8a3-4e68-96d3-502277642345.png)

**Comment by cinit** [comment]
是混淆的客户端吗? 有没有 anti-Xposed 之类的 feature?

**Comment by Ecalose** [comment]
唔，在2.1.1版本的it.owlgram.android也是如此

**Comment by cinit** [comment]
f1ab5c8fc2088380eb19089e5405d952db5d2d9e
