### ISSUE TITLE
希望增加“隐藏已屏蔽用户在群组中的发言”的功能

### ISSUE THREAD

**Issue by 6ur9er** [cinit/TMoe#40]
如题，好多广告机器人被屏蔽后在群组里面发言仍然能看见，之前不记得在哪里见过这项功能，现在找不到了，希望能加进TMoe里面，个人觉得这个功能很实用，望采纳，谢谢。
![Screenshot_20220711_093638](https://user-images.githubusercontent.com/103239502/178659130-7743e2a4-92f6-4017-87d4-b49947dc31ca.jpg)

**Comment by cracky5322** [comment]
> 有这个功能？第三方tg都没见过

確實有

**Comment by wzgrx** [comment]
> > 有这个功能？第三方tg都没见过
> 
> 確實有

列举一下？那个第三方，或者插件，或者修改版？
你光说有什么用？我还说有破解服务器的功能呢

**Comment by cracky5322** [comment]
> > > 有这个功能？第三方tg都没见过
> > 
> > 
> > 確實有
> 
> 列举一下？那个第三方，或者插件，或者修改版？ 你光说有什么用？我还说有破解服务器的功能呢

是是是，您說的對，看您急的

**Comment by cracky5322** [comment]
> > > > > 有这个功能？第三方tg都没见过
> > > > 
> > > > 
> > > > 確實有
> > > 
> > > 
> > > 列举一下？那个第三方，或者插件，或者修改版？ 你光说有什么用？我还说有破解服务器的功能呢
> > 
> > 
> > 是是是，您說的對，看您急的
> 
> 真和sb一样，凭空想象个功能让开发者加？您怎么不自己做这个功能？张口就来，什么乞丐

是是是，您說的對，看您急的

**Comment by cracky5322** [comment]
> > > > > > > 有这个功能？第三方tg都没见过
> > > > > > 
> > > > > > 
> > > > > > 確實有
> > > > > 
> > > > > 
> > > > > 列举一下？那个第三方，或者插件，或者修改版？ 你光说有什么用？我还说有破解服务器的功能呢
> > > > 
> > > > 
> > > > 是是是，您說的對，看您急的
> > > 
> > > 
> > > 真和sb一样，凭空想象个功能让开发者加？您怎么不自己做这个功能？张口就来，什么乞丐
> > 
> > 
> > 是是是，您說的對，看您急的
> 
> nt东西别复读了，ww回家吃奶，ok？

口嗨的人肯定沒 commit

轉述小群群內發言

**Comment by cracky5322** [comment]
> > > > > > > > > 有这个功能？第三方tg都没见过
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 確實有
> > > > > > > 
> > > > > > > 
> > > > > > > 列举一下？那个第三方，或者插件，或者修改版？ 你光说有什么用？我还说有破解服务器的功能呢
> > > > > > 
> > > > > > 
> > > > > > 是是是，您說的對，看您急的
> > > > > 
> > > > > 
> > > > > 真和sb一样，凭空想象个功能让开发者加？您怎么不自己做这个功能？张口就来，什么乞丐
> > > > 
> > > > 
> > > > 是是是，您說的對，看您急的
> > > 
> > > 
> > > nt东西别复读了，ww回家吃奶，ok？
> > 
> > 
> > 口嗨的人肯定沒 commit
> > 轉述小群群內發言
> 
> 皇上不急太监急？儿子这么急？笑死我了

是是是，您說的對，看您急的

**Comment by cinit** [comment]
由于屏蔽他人群内发言可能引起不必要的误会，且此功能违反 [ToS](https://telegram.org/tos) ，所以暂不考虑。
