### ISSUE TITLE
Not working in latest NekoX client

### ISSUE THREAD

**Issue by gjf** [cinit/TMoe#59]
Latest NekoX release (v9.3.3-preview01, https://github.com/NekoX-Dev/NekoX/releases/tag/v9.3.3-preview01) shows TMoe Settings but it cannot be opened.

**Comment by zhuoshao000** [comment]
> Latest NekoX release (v9.3.3-preview01, https://github.com/NekoX-Dev/NekoX/releases/tag/v9.3.3-preview01) shows TMoe Settings but it cannot be opened.

同样9.3.3版本我的TMoe设置正常

**Comment by gjf** [comment]
Really weird... which TMoe build are you using? I have attached mine, could you please check? 
[TMoe_sign.zip](https://github.com/cinit/TMoe/files/10556343/TMoe_sign.zip)

**Comment by cinit** [comment]
Please provide Xposed log when reporting a bug.

**Comment by cinit** [comment]
Try this https://github.com/cinit/TMoe/actions/runs/4064741131

**Comment by gjf** [comment]
Yup it fixed the problem, thank you!
