### ISSUE TITLE
Add nekogram to scope

### ISSUE THREAD

**Issue by pokurt** [cinit/TMoe#6]
Hi, can you please add `tw.nekomimi.nekogram` to the scope, it would be awesome!

**Comment by cracky5322** [comment]
> Hi, can you please add `tw.nekomimi.nekogram` to the scope, it would be awesome!

tw.nekomimi.nekogram prohibits hooks, so it cannot be added

**Comment by pokurt** [comment]
Oh noes. Hence I'll close this
